# 工作流名称
name: GitHub-Profile-Summary-Cards

on:
  # schedule:
    # 每24小时触发一次
    # - cron: "0 * * * *"

    # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # 开启手动触发
  workflow_dispatch:

jobs:
  # job id
  build:
    runs-on: ubuntu-latest
    name: generate
    permissions:
      contents: write

    steps:
      # 第一步，checkout 当前项目
      - uses: actions/checkout@v3
      # 第二步，引入目标 action: vn7n24fzkq/github-profile-summary-cards仓库中的 `release` 分支
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONALACCESSTOKENS }}
        with:
          USERNAME: ${{ github.repository_owner }}
